### ISSUE TITLE
AttributeError: 'Box' object has no attribute 'n'

### ISSUE THREAD

**Issue by dragen1860** [tristandeleu/pytorch-maml-rl#10]
Dear author:
  When I try to run some experiements such as "Hopper-v2", it occures:
```python
Traceback (most recent call last):
  File "main.py", line 151, in <module>
    main(args)
  File "main.py", line 52, in main
    sampler.envs.action_space.n,
AttributeError: 'Box' object has no attribute 'n'

```
Why?

**Comment by tristandeleu** [comment]
The only environments working with this implementation right now are the ones provided in [`envs`](https://github.com/tristandeleu/pytorch-maml-rl/tree/master/maml_rl/envs), which are the environment defined in the two papers I am referencing in the README. MAML needs a gym environment where one can define different tasks. If you want to make something similar for Hopper, I suggest you have a look at the [MuJoCo environments](https://github.com/tristandeleu/pytorch-maml-rl/tree/master/maml_rl/envs/mujoco) to adapt Hopper with a similar API. PR would be really appreciated if you make it work!
