### ISSUE TITLE
How do gym.make go to envs/mujoco/ant.py or half_cheetah.py

### ISSUE THREAD

**Issue by dragen1860** [tristandeleu/pytorch-maml-rl#11]
Dear author:
   I have a small question when trying to understand your code.
   I saw you make env by call:
```python
def make_env(env_name):
	"""
	return a function
	:param env_name:
	:return:
	"""
	def _make_env():
		return gym.make(env_name)

	return _make_env


```
However, you dont call `ant.py` or `half_cheetah.py` explicitly. So I wonder How do the `gym` know you have implemented this class `HalfCheetahDirEnv` and `HalfCheetahVelEnv` etc?

**Comment by tristandeleu** [comment]
In gym you can register custom environments so that you can call them with `gym.make`. The registrations are done [here](https://github.com/tristandeleu/pytorch-maml-rl/blob/master/maml_rl/envs/__init__.py).
