### ISSUE TITLE
What's the goal to close self.work_remotes in subproc_vec_env.py

### ISSUE THREAD

**Issue by dragen1860** [tristandeleu/pytorch-maml-rl#12]
I found you establish 8 mp.Pipe() with 
```python
self.remotes, self.work_remotes = zip(*[mp.Pipe() for _ in env_factory])
```
But then you close all another  duplex point by:
```python
		for remote in self.work_remotes:
			remote.close()
```
I wonder could u explain this?

**Comment by tristandeleu** [comment]
I am not very familiar with this. But if I understand correctly, pipes are two way communication channels. In our case, we only need that communication to be one way, so we are closing one end of the pipes.
