### ISSUE TITLE
clean and nice implementation, could you extend to promp

### ISSUE THREAD

**Issue by Andrewtor** [tristandeleu/pytorch-maml-rl#21]
Thanks for this nice and readable implementation of meta learning algorithm, could you extend it to [ProMP](https://github.com/jonasrothfuss/ProMP)?

**Comment by tristandeleu** [comment]
Hi! Thank you for the kind words! I am looking at ProMP and I will eventually try to implement it in Pytorch. Unfortunately this won't probably be high priority on my list at the moment. However PR are very welcome for this if someone wants to get a hand at it!

**Comment by Andrewtor** [comment]
Will try a PR!
