### ISSUE TITLE
what's the purpose of len(self) in batchepisode when sample

### ISSUE THREAD

**Issue by Andrewtor** [tristandeleu/pytorch-maml-rl#22]
What's the purpose of using `len(self)` in [sampling](https://github.com/tristandeleu/pytorch-maml-rl/blob/master/maml_rl/episode.py#L26), I'm confused since we have already provide batch_size. With this `len(self)` , sampled data's shape would be `[len(self), batch_size, state_dim]`, which I can not understand.

**Comment by tristandeleu** [comment]
The object `BatchEpisode` contains a batch of multiple episodes. The length of `BatchEpisode` is the maximum length of each episode in the batch.

**Comment by Andrewtor** [comment]
Thanks, I understand `BatchEpisode` contains a batch of episodes , but why the length of `BatchEpisode` is equals to `len(self)` and is equals to the episode length?

**Comment by fengredrum** [comment]
@Andrewtor This code `    def __len__(self):
        return max(map(len, self._rewards_list))` overrides the original `len()` method, and returns the max length of `self._rewards_list`. :)

**Comment by Andrewtor** [comment]
@fengredrum Got it, thank you so much!!!
