### ISSUE TITLE
Are benchmarks available?

### ISSUE THREAD

**Issue by quanvuong** [tristandeleu/pytorch-maml-rl#29]
Thank you for the repo!

I was wondering if the repo obtains the same performance as reported in the papers on the DRL benchmarks?

**Comment by tristandeleu** [comment]
Thanks for the kind words!

For the benchmarks, unfortunately I don't have anything "official" as a point of comparison with the original paper. From experiment with `HalfCheetahVel` and `HalfCheetahDir`, the results after 1000 meta-training updates seem to match the results from the original paper. There is unfortunately an issue with the `Ant` tasks (`AntDir` and `AntVel`), for which I have never been able to get good results (there is another related issue #25 ), and never been able to match the performance from [the original repo](https://github.com/cbfinn/maml_rl).

I think @katerakelly might have used this code in her [latest paper](https://arxiv.org/abs/1903.08254) for the MAML-TRPO baseline. If that's the case (pinging @katerakelly just in case), then this paper also includes other experiments on Humanoid and Walker, and you could probably expect similar performances as in Figure 9.

But I think it would be a great idea to have a more principled benchmark as part of the repo for comparison with the original paper.

**Comment by katerakelly** [comment]
We actually did not end up using this repo for our MAML-TRPO experiments. We ended up using the implementation in https://github.com/jonasrothfuss/ProMP since that has ProMP also.

**Comment by quanvuong** [comment]
Thank you all for your comments! They’re super helpful.

**Comment by tristandeleu** [comment]
That's good to know, thank you @katerakelly!
