### ISSUE TITLE
Question about regression in baseline

### ISSUE THREAD

**Issue by hzyjerry** [tristandeleu/pytorch-maml-rl#35]
In https://github.com/tristandeleu/pytorch-maml-rl/blob/master/maml_rl/baseline.py#L44-L45, is there any particular reason to multiplying `featmat.t()`? In other words, is there any drawback to just doing `torch.gels(torch.matmul(returns), torch.matmul(featmat) + reg_coeff * eye)`?
Thanks in advance for your insight!

**Comment by tristandeleu** [comment]
These are the [normal equations](https://en.wikipedia.org/wiki/Ordinary_least_squares#Matrix/vector_formulation) to solve a regularized linear model, which is `(X^T * X + \lambda * I)^-1 * X^T * y`, so you need this `featmat.t()`.

**Comment by hzyjerry** [comment]
Awesome thanks!
