### ISSUE TITLE
Restoring model

### ISSUE THREAD

**Issue by timediv** [tristandeleu/pytorch-maml-rl#36]
Currently there is no way to restore a saved model and only do testing (fast adaptation), correct?

**Comment by tristandeleu** [comment]
No there is no way to restore the model at the moment unfortunately. This was on my list of things to update here for ages, and I'm sorry I haven't come around to doing that properly.
However check the script in https://github.com/tristandeleu/pytorch-maml-rl/issues/15#issuecomment-456728429 for an example of how to load and test the model.

**Comment by timediv** [comment]
I have implemented a testing procedure and will create a pull request when I got time to clean it up.

**Comment by BBDrive** [comment]
hello, have you implemented the test procedure about restoring a saved model? I want to learn something about it.

**Comment by tristandeleu** [comment]
I am closing this issue since the new version of the code now includes a script for testing. If there is any issue with this script, feel free to open a new issue.
