### ISSUE TITLE
builtins.AttributeError: 'NoneType' object has no attribute 'timestep_limit'？？

### ISSUE THREAD

**Issue by wang88256187** [tristandeleu/pytorch-maml-rl#37]

**Comment by Ji4chenLi** [comment]
I encountered the same issue. Have you solved it yet?

**Comment by tristandeleu** [comment]
This looks like a problem with Gym. Can you give me more details about the command you are running and your version of Gym?

**Comment by wang88256187** [comment]
Thx your reply. I have solved this problem,it is surely because of the gym version




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tristan Deleu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 晚上9:08
收件人:&nbsp;"tristandeleu/pytorch-maml-rl"<pytorch-maml-rl@noreply.github.com&gt;;
抄送:&nbsp;"461791315"<461791315@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tristandeleu/pytorch-maml-rl] builtins.AttributeError: 'NoneType' object has no attribute 'timestep_limit'？？ (#37)




This looks like a problem with Gym. Can you give me more details about the command you are running and your version of Gym?
