### ISSUE TITLE
pytorch 1.3 and python 3.8

### ISSUE THREAD

**Issue by mfe7** [tristandeleu/pytorch-maml-rl#47]
pip couldn't find a pytorch 1.3 version with my python 3.8 virtualenv, but the requirements.txt file installed just fine when i used python 3.6.9. maybe one fix is to update the readme to limit the compatible python versions to 3.5-3.6 (maybe 3.7, but i didn't test that)

**Comment by tristandeleu** [comment]
Thank you for the bug report. This is because I was using a conservative version in `requirements.txt` which is probably not necessary. I will update it, but you can probably use the latest version of PyTorch (1.6).
