### ISSUE TITLE
what is the mean of train_episodes and valid_episodes?

### ISSUE THREAD

**Issue by GeorgeDUT** [tristandeleu/pytorch-maml-rl#54]
the test.py writes a file about "task", "train_episodes", "valid_episodes". "train_episodes", "valid_episodes" are the total rewards of an episode?

**Comment by tristandeleu** [comment]
Yes `train_returns` and `valid_returns` are the (undiscounted) cumulated rewards for each task and each episode.

**Comment by GeorgeDUT** [comment]
what is the difference between "train_return" and "valid_return"?

**Comment by tristandeleu** [comment]
`train_return` correspond to the returns for the trajectories sampled with the initial policy (before adaptation), and `valid_return` correspond to the returns for the trajectories sampled with the adapted policy. Taking the notations of [the paper](https://arxiv.org/abs/1703.03400) (Algorithm 3), `train_returns` correspond to the returns on `D` and `valid_returns` correspond to the returns on `D'`.

**Comment by GeorgeDUT** [comment]
thanks so much, I get it
