### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by dragen1860** [tristandeleu/pytorch-maml-rl#6]
```
i@d:~/rl/pytorch-maml-rl$ python main.py --env-name HalfCheetahDir-v1 --num-workers 8 --fast-lr 0.1 --max-kl 0.01 --fast-batch-size 20 --meta-batch-size 40 --num-layers 2 --hidden-size 100 --num-batches 1000 --gamma 0.99 --tau 1.0 --cg-damping 1e-5 --ls-max-steps 15 --output-folder maml-halfcheetah-dir --device cuda

Traceback (most recent call last):
  File "main.py", line 138, in <module>
    main(args)
  File "main.py", line 29, in main
    config = {k: v for (k, v) in vars(args).iteritems() if k != 'device'}
AttributeError: 'dict' object has no attribute 'iteritems'
```

I followed your readme but the error occurs. Any tips, Thanks.

**Comment by dendisuhubdy** [comment]
@dragen1860 are you using Python 3+?

**Comment by dragen1860** [comment]
yes. @dendisuhubdy

**Comment by dendisuhubdy** [comment]
@dragen1860 `iteritems()` was removed from Python3, the codebase I believe is running on Python 2.7. Change `main.py` line 29 to `config = {k: v for (k, v) in vars(args).tems() if k != 'device'}`, let me know.

**Comment by dendisuhubdy** [comment]
Your `config` is a tuple without a `update` attribute, `config` is supposed to be a `dict`. Did you remove the `{ ... }` from `config = { ..... }`

**Comment by dragen1860** [comment]
oh, I solved it . 
Can you update the readme to append a guide of how to install mujoco?
```
gym.error.DependencyNotInstalled: No module named 'mujoco_py'. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)

```

**Comment by tristandeleu** [comment]
Oh my bad, I did that change locally but didn't committed it. Thank your for the feedback!
As for installation for Mujoco, this is also something I forgot in the requirements (`gym[mujoco]` instead of `gym`). I will make that change. As for the installation of the software itself, I suggest going through the steps from the [mujoco-py](https://github.com/openai/mujoco-py) readme.
