### ISSUE TITLE
Could u kindly implement pytorch-maml part?

### ISSUE THREAD

**Issue by dragen1860** [tristandeleu/pytorch-maml-rl#7]
Hi, I found it's very difficult to implement the code in MAML.
Currently my implementation has some bugs: https://github.com/dragen1860/MAML-Pytorch
Im not sure how to do 2nd derivate in MAML.
And also I search other implementation in pytorch and there are more severe bugs in them.

So would u kindly publish a correct verion of pytorch-maml or You CAN just **review my implementation** above and help me see any bugs?
Thanks so much.

**Comment by dendisuhubdy** [comment]
@dragen1860 that is something pretty rude to say.

**Comment by tristandeleu** [comment]
Hi @dragen1860 , I'm sorry I haven't worked on the supervised setting of MAML unfortunately, so I would be of much help here I guess. Check the way [policies](https://github.com/tristandeleu/pytorch-maml-rl/tree/master/maml_rl/policies) are implemented to get some inspiration on how to handle the parameter adaptation on the learner (which I guess would be similar in the supervised case). The second derivative is computed automatically through the automatic differentiation of Pytorch (no specific tricks required, other than `create_graph=True` when computing the gradient for the adaptation).

I also have seen [this implementation](https://github.com/katerakelly/pytorch-maml) which seems popular, but I haven't tried it myself. Hope this will help you!
